### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-qringbuf#3]
As there doesn't seem to be a good template to use for PL repositories, [I put together the following](https://github.com/ipfs/go-qringbuf/commit/56051fbaddd0cb53ecd9e88909c870ab24c57bff?short_path=37854d1#diff-37854d19817c792316d481f5beb93cc7)

As my legalese is not *that* great, it would be nice if someone else looks over this and points out anything wrong/inconsistent. Once validated we could use this to fix several other repositories with a less-than-ideal licensing story.

@ianjdarrow it was suggested you know a lot about this topic - could you chime in? Thanks!

~P.S. The two CIDs I am referencing in the `.md` are not pinned... I don't know how ;)~ both CIDs are now pinned

/cc @achingbrain @andrew @andyschwab @mikeal

**Comment by ribasushi** [comment]
One thing that gives me pause, is that when we say `Apache2` in SPDX - everything is clear. But it [appears to be less so for `MIT`](https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT):
> There are many MIT variants, all of which are functionally identical

🙀🙀🙀

**Comment by andyschwab** [comment]
From https://spdx.org/licenses/, it looks like SPDX allows designation of multiple forms of the MIT license.

The explicit "MIT" mapping in SPDX from https://spdx.org/licenses/MIT.html#licenseText points to https://opensource.org/licenses/MIT, which is the one referenced in the LICENSE file as well, so it seems coherent.

So it may not be as ambiguous as it seems.

**Comment by ribasushi** [comment]
With @hsanjuan including the licensing verbatim in https://github.com/ipfs/ipfs-repository-template I guess the issue is settled. Closing.
