### ISSUE TITLE
Avoid locking while reading

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-qringbuf#7]
Currently, this library holes the global lock while reading from the input reader. Given that the input reader can block for an arbitrary amount of time, this could significantly limit the libraries throughput if the reader is slow for some reason.

Given the fact that the buffer has a fixed size, it should be pretty simple for `NextRegion` to simply avoid reading the part of the buffer being used by the `collector` goroutine.

**Comment by ribasushi** [comment]
@Stebalien hmmmm... I don't think I do hold a lock...? Could you link me to the relevant code part?

**Comment by Stebalien** [comment]
Read here:

https://github.com/ipfs/go-qringbuf/blob/34b4291cc14a9bcda9b38641ce2c1b5e6ce9caa3/qringbuf.go#L762-L764

Lock here:

https://github.com/ipfs/go-qringbuf/blob/34b4291cc14a9bcda9b38641ce2c1b5e6ce9caa3/qringbuf.go#L633

**Comment by ribasushi** [comment]
Closed by https://github.com/ipfs/go-qringbuf/commit/cba208e8
